name: Debian Packer Example

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deb-control-file-build:
    name: Generate Debian Package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # To Do:
        # Generate Example Control File
        # Prepare Example Package Resources
        # Run Debian Packager
        # Upload Generated Package as Artifact